"use client";

import React, { useState } from "react";
import { MarineHeader } from "@/components/marine/marine-header";
import { HeroKPIChart } from "@/components/marine/hero-kpi-chart";
import { VolumeSpectrumCard } from "@/components/marine/volume-spectrum-card";
import { DonutBreakdownCard } from "@/components/marine/donut-breakdown-card";
import { StackedKPICard } from "@/components/marine/stacked-kpi-card";
import { MaritimeLeaderboardCard } from "@/components/marine/maritime-leaderboard-card";
import { MarineSimulatorModal } from "@/components/marine/marine-simulator-modal";

// JSON Data contracts generated by Python ML pipeline (ml/src/export_insights.py)
import heroData from "@/data/marine_hero.json";
import spectrumData from "@/data/marine_spectrum.json";
import breakdownsData from "@/data/marine_breakdowns.json";
import kpiData from "@/data/marine_kpis.json";
import leaderboardData from "@/data/marine_leaderboard.json";
import modelData from "@/data/marine_model.json";

export default function MarineDashboardPage() {
  const [isSimulatorOpen, setIsSimulatorOpen] = useState(false);

  return (
    <div className="min-h-screen bg-ocean-900 text-white flex flex-col selection:bg-cyan-500 selection:text-ocean-950 font-sans">
      {/* Top Header */}
      <MarineHeader onOpenSimulator={() => setIsSimulatorOpen(true)} />

      {/* Main Marine Dashboard Grid (Direct match to reference layout) */}
      <main className="flex-1 max-w-[1600px] w-full mx-auto px-4 sm:px-6 py-6 space-y-5">
        {/* ROW 1: Hero KPI Area Chart | Volume Spectrum | Fleet Donut */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
          {/* Top-Left: Hero Metric with Area Chart */}
          <div className="lg:col-span-4">
            <HeroKPIChart data={heroData} />
          </div>

          {/* Top-Center: Volume Spectrum Bins */}
          <div className="lg:col-span-4">
            <VolumeSpectrumCard data={spectrumData} />
          </div>

          {/* Top-Right: Fleet Operations Donut Breakdown */}
          <div className="lg:col-span-4">
            <DonutBreakdownCard data={breakdownsData.fleet_donut} />
          </div>
        </div>

        {/* ROW 2: Stacked KPIs | Species Donut Breakdown | Port Leaderboard */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-stretch">
          {/* Bottom-Left: Stacked Metric Cards (Conversations & Active Fleet) */}
          <div className="lg:col-span-3">
            <StackedKPICard data={kpiData} />
          </div>

          {/* Bottom-Center: Species Classification Donut */}
          <div className="lg:col-span-4">
            <DonutBreakdownCard data={breakdownsData.species_donut} />
          </div>

          {/* Bottom-Right: Regional Maritime Port Leaderboard */}
          <div className="lg:col-span-5">
            <MaritimeLeaderboardCard data={leaderboardData} />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-ocean-700/40 py-4 px-6 text-center text-[11px] text-ocean-400 bg-ocean-950">
        <div className="max-w-[1600px] mx-auto flex flex-col sm:flex-row items-center justify-between gap-2">
          <span>DOSM Datathon 2026 • Marine & Blue Economy Surveillance System</span>
          <div className="flex items-center space-x-3 text-ocean-400">
            <span>Next.js 14 App Router</span>
            <span>•</span>
            <span className="text-cyan-400 font-medium">Vercel Edge Optimized</span>
            <span>•</span>
            <span>Zero Cold Starts</span>
          </div>
        </div>
      </footer>

      {/* ML Bioeconomic Policy Simulator Modal */}
      <MarineSimulatorModal
        isOpen={isSimulatorOpen}
        onClose={() => setIsSimulatorOpen(false)}
        modelData={modelData}
      />
    </div>
  );
}
